version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.6.1
    steps:
      - checkout 
      - run: python3 url.py > output.txt
    store_artifacts:
      path: output.txt
      destination: output.txt